### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by Skoreto** [TeeJay-net/fitspirit#1]
nefungují háčky čárky v JSP

**Comment by TeeJay-net** [comment]
Bude potřeba rozdělit šablonu minimálně na 2 části - první bude hlavička, menu a patička, druhá  pak tělo, s tím, že hlavička proměnlivá nebude. Na to by mohl mít Spring nějakej šablonovací systém, kterej tohle podporuje, implementace je pak jednoduchá. A pak se v té jedné jediné hlavičce nastaví UTF-8.

**Comment by Skoreto** [comment]
Něco už jsem odkoukal z toho ukázkového projektu k injektování jednotlivých částí šablony. 

V .NET jsem to měl rozdělené na část pro nepřihlášeného uživatele a v authorizované části se měnilo menu podle role přihlášeného uživatele uživatele.

Zádrhele jsem zatím podrobně nezkoumal, to ti můžu ukázat ve škole. Teď jsem si chtěl jen vyzkoušet něco pushnout :)

**Comment by Skoreto** [comment]
Vyřešeno.
